### ISSUE TITLE
Unrecognized Regex Literals

### ISSUE THREAD

**Issue by jaydiablo** [douglascrockford/JSMin#11]
Given this if statement, the following snippets aren't seen as regex literals by JSMin:

``` c
if (theB == '/' && (theA == '(' || theA == ',' || theA == '=' ||
                            theA == ':' || theA == '[' || theA == '!' ||
                            theA == '&' || theA == '|' || theA == '?' ||
                            theA == '{' || theA == '}' || theA == ';' ||
                            theA == '\n')) {
```

Snippet #1:

``` javascript
var ex = +/w$/.test(resizing),
    ey = +/^n/.test(resizing);
```

In this case, when "theB" == "/", "theA" == "+" which isn't one of the conditions defined.

Snippet #2:

``` javascript
return /[",\n]/.test(text)
      ? "\"" + text.replace(/\"/g, "\"\"") + "\""
      : text;
```

In this case, "theA" == " " because of the return.

**Comment by Shazwazza** [comment]
I have a modified c# version of JSMin and have this problem (among others), you can see the result here:

https://github.com/Shazwazza/ClientDependency/blob/master/ClientDependency.Core/CompositeFiles/JSMin.cs

The fixes for this issue I've implemented seem ultra hacky but they seem to work, essentially adding 3 new chars to check in the above if: ' ', 'n', '+'
I have tests for this in there too ... now just need to see if more stuff has broken. 

There's a few other issues I've fixed with JSMin in there that have tests written for them too.
